config/routes.rb
Rails.application.routes.draw do
  resources :splits
  resources :results
  resources :entries
  resources :aims
  resources :seats
  resources :dockets
  resources :relays

  resources :events do
    member do
      post 'list'
      post 'seed'
    end
  end

  resources :invitations
  resources :supports
  resources :qualification_times
  resources :swimmers
  resources :standards
  resources :competitions
  resources :qualifications
  resources :disciplines
  resources :clubs
  resources :strokes
  resources :assignments
  resources :roles

  devise_for :users
  scope :admin do
    resources :users
  end

  get 'heats' => 'heats#index'
  get 'lanes' => 'lanes#index'

  get 'home/index'
  root to: 'home#index'
end

app/models/discipline.rb
class Discipline < ApplicationRecord

  has_many :events
    has_many :competitions, through: :events
    has_many :entries, through: :events
      has_many :results, through: :entries
  has_many :qualification_times
    has_many :qualifications, through: :qualification_times

  # FIXME: make sure no event or qualification_time is refering before delete

  DISTANCES = [25, 50, 100, 200, 400, 800, 1500]
  COURSES = ["TC", "SC", "LC"]
  STROKES = [
    "Freestyle",
    "Backstroke",
    "Breaststroke",
    "Butterfly",
    "Ind Medley"
  ]
  MODES = [ "I", "R" ] # Individual or Relay

  validates :distance, :course, :stroke, :mode, presence: true
  validates :distance, inclusion: DISTANCES
  validates :course, inclusion: COURSES
  validates :stroke, inclusion: STROKES
  validates :mode, inclusion: MODES

  # customize json representation
  def as_json(options = {})
    super(root: false, only: [:id], methods: [:results])
  end

  def is_relay?
    mode == "R"
  end

  def name
    sprintf("%s %s%dm (%s)", stroke, is_relay? ? "4x" : "", distance, course)
  end

  def nickname
    dict = {
    "Freestyle" => 'Free',
    "Backstroke" => 'Back',
    "Breaststroke" => 'Breast',
    "Butterfly" => 'Fly',
    "Ind Medley" => 'IM'
    }
    sprintf("%s%dm %s", is_relay? ? "4x" : "", distance, dict[stroke])
  end

  def nickname_course
    "#{nickname} (#{course})"
  end

  def to_words
    if is_relay? then
      sprintf("4x%dm %s %s Relay", distance, course, stroke == "Ind Medley" ? "Medley" : stroke)
    else
      sprintf("%dm %s %s", distance, course, stroke)
    end
  end

  def distance_stroke
    if is_relay? then
      sprintf("4x%dm %s Relay", distance, stroke == "Ind Medley" ? "Medley" : stroke)
    else
      sprintf("%dm %s", distance, stroke)
    end
  end

  def distance_course_stroke
    if is_relay? then
      sprintf("4x%dm %s %s Relay", distance, course, stroke == "Ind Medley" ? "Medley" : stroke)
    else
      sprintf("%dm %s %s", distance, course, stroke)
    end
  end

  def distance_in_words
    ((is_relay? ? "4x" : "") + "%dm") % distance
  end

  def stroke_in_words
    ("%s" + (is_relay? ? " Relay" : "")) % ((is_relay? and stroke == "Ind Medley") ? "Medley" : stroke)
  end

  def to_s
    to_words
  end

  def to_hash
    keys = %w(distance course stroke mode)
    attributes.select { |k, v| keys.include? k }
  end

  def opposite
    hash = to_hash
    hash['course'] = { 'SC' => 'LC', 'LC' => 'SC' }[hash['course']]
    Discipline.where(hash).first
  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_discipline, only: [:edit, :update, :destroy]

  # GET /disciplines
  # GET /disciplines.json
  def index
    authorize! :index, Discipline
    @disciplines = Discipline.includes(:events, :qualification_times)
    if params[:club_id]
      @club = Club.find(params[:club_id])
    end
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
    @discipline = Discipline.includes(
      { qualification_times: :qualification },
      :competitions,
      { results: { entry: { subject: [:swimmer, { invitation: :club }] } } }
    ).find(params[:id])
    authorize! :show, @discipline
    @qts_by_qualification = @discipline.qualification_times.group_by(&:qualification)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discipline }
    end
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
    authorize! :new, @discipline
  end

  # GET /disciplines/1/edit
  def edit
    authorize! :edit, @discipline
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)
    authorize! :create, @discipline

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    authorize! :update, @discipline
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    authorize! :destroy, @discipline
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:gender, :distance, :course, :stroke, :mode, :differential)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= form_with(model: discipline, local: true) do |form| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.number_field :distance %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course %>
  </div>

  <div class="field">
    <%= form.label :stroke %>
    <%= form.text_field :stroke %>
  </div>

  <div class="field">
    <%= form.label :mode %>
    <%= form.text_field :mode %>
  </div>

  <div class="field">
    <%= form.label :differential %>
    <%= form.number_field :differential %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<h1>Disciplines</h1>

<% @disciplines.group_by(&:course).each do |course, disciplines_course| %>

  <h2><%= { 'SC' => "Short", 'LC' => "Long", 'TC' => "Tiny" }[course] %> Course</h2>

  <ul>
  <% disciplines_course.sort_by(&:mode).group_by(&:mode).each do |mode, disciplines_mode| %>
  <% disciplines_mode.sort_by { |x| Discipline::STROKES.index(x.stroke) }.group_by(&:stroke).each do |stroke, disciplines| %>

  <li><b><%= disciplines.first.stroke_in_words %>:</b>
  <%= raw disciplines.sort_by(&:distance).map { |discipline| link_to(discipline.distance_in_words, discipline) + " [#{discipline.events.size}|#{discipline.qualification_times.size}]" }.to_sentence %>.
  </li>

  <% end %>
  <% end %>
  </ul>
<% end %>

<hr />
<% if can? :create, Discipline %>
  <%= link_to 'New Discipline', new_discipline_path %>
<% end %>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<style>
  .axis, .label {
    font-family: arial;
    font-size: 0.8em;
  }

  path {
    fill: none;
    stroke: black;
    stroke-width: 2px;
  }

  .tick {
    fill: none;
    stroke: black;
  }

  circle {
    opacity: 0.6;
    stroke: none;
    fill: blue;
  }

  div.buttons {
    position: fixed;
    top: 150px;
    right: 20px;
  }

  div.buttons div {
    background-color: rgb(255,156,156);
    padding: 3px;
    margin: 7px;
  }
</style>

<script type="text/javascript">
function draw(data) {

  "use strict";
  var margin = 75,
      width = 1000 - margin,
      height = 600 - margin;

  data = data.results.filter(function(d) { return d.time > 0; })

  var svg = d3.select("div#chart")
    .append("svg")
      .attr("width", width + margin)
      .attr("height", height + margin)
    .append("g")
      .attr("class", "chart");

  function get_id(d) {
    return d.id;
  }

  // x axis represents age
  function get_age(d) { return d.age_in_days / 365.25; }
  var age_extent = d3.extent(data, get_age);
  var age_scale = d3.scale.linear()
    .range([margin, width])
    .domain(age_extent);
  var age_axis = d3.svg.axis()
    .scale(age_scale);
  svg.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0," + height + ")")
    .call(age_axis);

  svg.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", width)
    .attr("y", height - 6)
    .text("Swimmer's age (years)");

  // y axis represents time
  function get_time(d) {
    return new Date(10 * d.time);  // milliseconds
  }
  var time_extent = d3.extent(data, get_time);
  var time_scale = d3.time.scale()
    .range([margin, height])
    .domain(time_extent);

  var format = d3.time.format("%M:%S");
  var time_axis = d3.svg.axis()
    .scale(time_scale)
    .tickFormat(format)
    .orient("left");
  svg.append("g")
    .attr("class", "y axis")
    .attr("transform", "translate(" + margin + ",0)")
    .call(time_axis);

  svg.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("y", margin + 12)
    .attr("x", -margin)
    .attr("transform", "rotate(-90)")
    .text("Time (mm:ss)");

  // add circles
  svg.selectAll("circle")
    .data(data, get_id)
    .enter()
    .append("circle")
    .attr("cx", function(d) { return age_scale(get_age(d)); })
    .attr("r", 5)
    .style("fill", function(d) { return d.gender == "M" ? 'red' : 'green'; } )
    .append("title")
    .text(function(d) { return d.name; });

  svg.selectAll("circle")
    .transition().duration(1500)
    .attr("cy", function(d) { return time_scale(get_time(d)); });

  // group results by club
  var nested = d3.nest()
    .key(function(d) { return d.symbol; })
    .entries(data);

  var buttons = d3.select("div#chart")
    .append("div")
      .attr("class", "buttons")
    .selectAll("div")
    .data(nested)
    .enter()
    .append("div")
    .text(function(d) { return d.key; });

  buttons.on("mouseover", function(d) {
    buttons.style("background", "rgb(255,156,156)")
      .style("color", "black");
    d3.select(this)
      .style("background", "blue")
      .style("color", "white");
    update(d.values);
  });

  function update(vals) {
    svg.selectAll("circle")
      .data(vals, get_id)
      .style("fill", "blue")
      .exit()
      .style("fill", "red")
  }
}
</script>


<h3><%= link_to 'Disciplines', disciplines_path %></h3>

<h1><%= @discipline %></h1>

<% if @discipline.differential %>
<p>
  <b>Differential:</b> <%= time_to_msc @discipline.differential %>
</p>
<% end %>

<h2>Chart</h2>

<div id="chart"></div>
<script type="text/javascript">
  d3.json("<%= discipline_path(@discipline, :json) %>", draw);
</script>

<% @discipline.events.group_by(&:gender).each do |gender, events| %>

<h2><%= { 'F' => "Girls", 'M' => "Boys", 'X' => "Mixed" }[gender] %> Competitions</h2>

<ul>
<% events.sort_by { |x| x.competition.date }.reverse_each do |event| %>
<% competition = event.competition %>
<li><%= competition.date %>: <%= link_to competition.name, event %> (<%= competition.location %>)</li>
<% end %>
</ul>
<% end %>


<h2>Qualification Times</h2>

<% @qts_by_qualification.each do |qualification, times| %>
<h3><%= link_to qualification.name, qualification %></h3>
<% times.group_by(&:gender).each do |gender, times_by_gender| %>
<table class="fact-sheet">
<tr class="times-major">
  <th><%= { 'F' => "Girls", 'M' => "Boys", 'X' => "Mixed" }[gender] %></th>
  <td></td>
</tr>
  <% times_by_gender.sort_by(&:age_min).each do |time| %>
<tr class="times-major">
   <th align="right"><%= ages_to_words(time.age_range) %>: </th>
   <td align="right"><%= time %></td>
</tr>
  <% end %>
</table>
<% end %>
<% end %>

<hr />
<% if can? :update, @discipline %>
<%= link_to 'Edit', edit_discipline_path(@discipline) %> |
<% end %>
<% if can? :destroy, @discipline %>
<%= link_to 'Destroy', @discipline, :confirm => 'Are you sure?', :method => :delete %> |
<% end %>
<%= link_to 'Back', disciplines_path %>