config/routes.rb
Rails.application.routes.draw do
  resources :splits
  resources :results
  resources :entries
  resources :aims
  resources :seats
  resources :dockets
  resources :relays

  resources :events do
    member do
      post 'list'
      post 'seed'
    end
  end

  resources :invitations
  resources :supports
  resources :qualification_times
  resources :swimmers
  resources :standards
  resources :competitions
  resources :qualifications
  resources :disciplines
  resources :clubs
  resources :strokes
  resources :assignments
  resources :roles

  devise_for :users
  scope :admin do
    resources :users
  end

  get 'heats' => 'heats#index'
  get 'lanes' => 'lanes#index'

  get 'home/index'
  root to: 'home#index'
end

app/models/competition.rb
class Competition < ApplicationRecord

  has_many :events, dependent: :destroy
    has_many :disciplines, through: :events
    has_many :entries, through: :events
    has_many :results, through: :events
  has_many :standards, dependent: :destroy
    has_many :qualifications, through: :standards
  has_many :invitations, dependent: :destroy
    has_many :dockets, through: :invitations
      has_many :swimmers, through: :dockets
    has_many :relays, through: :invitations
    has_many :clubs, through: :invitations

  default_scope { order(:date) }
  validates :name, :date, :length, presence: true
  validates :course, inclusion: Discipline::COURSES

  def individual_events
    events.select { |x| not x.is_relay? }
  end

  def relay_events
    events.select { |x| x.is_relay? }
  end

  def season
    year = date.year + (date.month > 8 ? 1 : 0)
    return "%d/%02d" % [year-1, year % 100]
  end

  def days
    1..length
  end

  def first_day
    date
  end

  def last_day
    date + (length - 1)
  end

  def dates
    "#{first_day}" + (length > 1 ? " - #{last_day}" : "")
  end

  # which competitions lie ahead of us?
  def relative_date
    [:current, :recent, :future][((Date.today - date)/length).floor <=> 0]
  end

  def to_s
    "%s: %s, %s" % [dates, name, location]
  end

  def location_dates
    "#{location}, #{dates}"
  end

  # number of individual entries
  def i_entries_count
    dockets.map(&:entries).flatten.count
  end

  # number of relay entries
  def r_entries_count
    relays.map(&:entries).flatten.count
  end

  # SDIF parts
  def to_a0
    line = {
      mark: "A0",
      orgc: "8",
      vers: "%-8s" % "V3",
      filc: "02",
      gap0: "%-30s" % "Meet Results",
#      snam: "%-20s" % "GalaMan",
      snam: "%-20s" % "Hy-Tek, Ltd",
#      sver: "%-10s" % "v3.1",
      sver: "%-10s" % "WMM 4.0Eh",
#      cnam: "%-20s" % "BlueFin S.C.",
      cnam: "%-20s" % "Hy-Tek, Ltd",
#      cpho: "%12s" % "",
      cpho: "%12s" % "866-456-5111",
      date: Time.now.strftime("%m%d%Y"),
      gap1: "%42s" % "MM40  ",
      subm: "  ",
      gap2: "   ",
    }
    line = SDIF[line[:mark]][:keys].map { |key| line[key] }.join
    line[-4, 4] = Format.checksum(line)
    line
  end

  def to_b1
    line = {
      mark: "B1",
      orgc: "8",
      gap0: "%8s" % "",
      name: "%-30s" % name,
      adr1: "%-22s" % "",
      adr2: "%-22s" % "",
      city: "%-20s" % location,
      stat: "%2s" % "",
      zipc: "%10s" % "",
      ctry: "%3s" % "",
      meet: " ",
      dat0: date.strftime("%m%d%Y"),
      dat1: (date + (length - 1)).strftime("%m%d%Y"),
      alti: "%4d" % 0,
      gap1: "%8s" % "",
      crse: "S",
      gap2: "%-10s" % " 000",
    }
    line = SDIF[line[:mark]][:keys].map { |key| line[key] }.join
    line[-4, 4] = Format.checksum(line)
    line
  end

  def to_z0
    line = {
      mark: "Z0",
      orgc: "8",
      gap0: "Meet Res",
      filc: "02",
      note: "%-30s" % "Successful Build on #{Date.today}",
      nrbs: "%3s" % 1,
      nrms: "%3s" % 1,
      nrcs: "%4s" % invitations.count,
      nrts: "%4s" % invitations.count,
      nrds: "%6s" % i_entries_count,
      nrss: "%6s" % dockets.count,
      nres: "%5s" % r_entries_count,
      nrfs: "%6s" % 0,
      nrgs: "%6s" % 0,
      btch: "%-5s" % "",
      news: "%-3s" % "",
      rens: "%-3s" % "",
      chgs: "%-3s" % "",
      dels: "%-3s" % "",
      gap1: "%-57s" % "",
    }
    line = SDIF[line[:mark]][:keys].map { |key| line[key] }.join
    line[-4, 4] = Format.checksum(line)
    line
  end

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    authorize! :index, Competition
    @competitions = Competition.all
    @competitions_by_season = @competitions.group_by(&:season)
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    authorize! :show, @competition
    @invitations = @competition.invitations.includes(:club, :dockets, :relays, :entries)
    @events = @competition.events.includes(:entries, :discipline)
    respond_to do |format|
      format.html # show.html.erb
      format.tex
    end
  end

  # GET /competitions/new
  def new
    @competition = Competition.new(length: 1)
    authorize! :new, @competition
  end

  # GET /competitions/1/edit
  def edit
    authorize! :edit, @competition
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)
    authorize! :create, @competition

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    authorize! :update, @competition
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    authorize! :destroy, @competition
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :location, :course, :age_up, :date, :length, :source, :source_url, :source_date)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_events.html.erb
<h3 class="edit-head">Events</h3>
<% if can? :update, @competition %>
  <div class="edit">
    <%= link_to '[+]', new_event_path(competition_id: @competition) %>
  </div>
<% end %>
<br />

<% events = @events.group_by(&:day) %>
<% @competition.days.each do |day| %>
<% if events.include?(day) %>
<% if @competition.length > 1 %>
<h4>Day <%= day %> (<%= @competition.date + (day - 1).days %>)</h4>
<% end %>
<table class="fact-sheet">
  <tr class="fact-major">
    <th>No.</th>
    <th>Discipline</th>
    <th>Gender, Age</th>
    <th></th>
    <% if can? :update, @competition %>
      <th></th>
      <th></th>
    <% end %>
  </tr>

<% events[day].each do |event| %>
  <tr class="fact-major">
    <td align="right"><%= ordinal_number(event.pos) %></td>
    <td><%= link_to event.discipline.to_words, event %></td>
    <td>
      <%= gender_word event.gender %>,
      <%= ages_to_words(event.age_range) %>
    </td>
    <td align="right"><%= pluralize(event.entries.size, 'entry') %></td>
    <% if can? :update, @competition %>
      <td><%= link_to image_tag('delete.png', class: "icon"), event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= event.seeded? ? "x" : "o" %></td>
    <% end %>
  </tr>
<% end %>
</table>
<% end %>
<% end %>

app/views/competitions/_form.html.erb
<%= form_with(model: competition, local: true) do |form| %>
  <% if competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %><br />
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :course %><br />
    <%= form.select :course, Discipline::COURSES %>
  </div>

  <div class="field">
    <%= form.label :date, 'Start Date' %><br />
    <%= form.date_select :date, order: [:day, :month, :year] %>
  </div>

  <div class="field">
    <%= form.label :length %><br />
    <%= form.text_field :length, size: 4 %> Days
  </div>


  <div class="field">
    <%= form.label :age_up, 'Age Up' %><br />
    <%= form.date_select :age_up,
	default: Date.today.end_of_year(),
	order: [:day, :month, :year] %>
  </div>

  <div class="field">
    <%= form.label :source %><br />
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :source_url %><br />
    <%= form.text_field :source_url %>
  </div>

  <div class="field">
    <%= form.label :source_date %><br />
    <%= form.date_select :source_date, :order => [:day, :month, :year] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/competitions/_invitations.html.erb
<h3 class="edit-head">Participating Clubs</h3>
<% if can? :update, @competition %>
  <div class="edit">
    <%= link_to '[+]', new_invitation_path(competition_id: @competition) %>
  </div>
<% end %>
<br />
<br />
<table class="fact-sheet">
<% @invitations.sort_by { |x| x.club.full_name }.each do |invitation| %>
  <tr class="fact-major">
    <td><%= link_to invitation.club.name, invitation %></td>
    <td align="right"><%= pluralize(invitation.dockets.size, 'swimmer') %> in</td>
    <td align="right"><%= pluralize(invitation.entries.size, 'event') %></td>
    <% if can? :update, @competition %>
      <td><%= link_to image_tag('delete.png', class: "icon"), invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/competitions/_qualifications.html.erb
<h3 class="edit-head">Qualification Standards:</h3>
<% if can? :update, @competition %>
  <div class="edit">
    <%= link_to '[+]', new_standard_path(competition_id: @competition) %>
  </div>
<% end %>

<ul style="padding: 0; margin: 0; display: inline;">
<% @competition.standards.each do |standard| %>
  <li style="list-style:none; display:inline; border: 1px solid blue; background: lightyellow; padding: 2px 4px; margin: 4px; border-radius: 4px;">
    <%= link_to standard.qualification.name, standard.qualification -%>
    <% if can? :destroy, @competition %>
      <%= link_to image_tag('delete.png', class: "icon"), standard, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<h1>Competitions</h1>

<% @competitions_by_season.reverse_each do |season, competitions| %>

<h2><%= season %></h2>

<table class="fact-sheet">
<% competitions.reverse_each do |competition| %>
  <tr class="fact-major">
    <td><%= competition.date %></td>
    <td><%= link_to competition.name, competition %>
    (<%= competition.location %>)</td>
  </tr>
<% end %>
</table>

<br />

<% end %>
<hr />

<% if can? :create, Competition %>
  <%= link_to 'New Competition', new_competition_path %>
<% end %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<h3><%= link_to 'Competitions', competitions_path %></h3>

<h1><%= @competition.name %></h1>

<p>
  <%= @competition.location %>
  (<%= @competition.dates %>, <%= @competition.course %>)<br />
</p>

<%= content_tag(:p, "Age up: #{@competition.age_up}.") if @competition.age_up %>

<% if @competition.source.present? %>
<p>
<b>Reference:</b>
<%= link_to @competition.source, @competition.source_url %>,
<%= @competition.source_date %>.
</p>
<% end %>

<% relay_count = @competition.relays.size %>
<% relay_text = (relay_count > 0 ? " and #{pluralize(relay_count, 'relay entry')}" : "") %>
<%= pluralize(@invitations.size, 'club has', 'clubs have') %> registered
<%= pluralize(@competition.dockets.size, 'swimmer') %> for
<%= pluralize(@competition.entries.size, 'individual entry') + relay_text + "." %>

<br />
<br />
<%= render 'qualifications' %>
<br />
<br />
<%= render 'invitations' %>
<br />
<br />
<%= render 'events' %>

<hr/>
<% if can? :update, @competition %>
  <%= link_to 'Edit', edit_competition_path(@competition) %> |
<% end %>
<% if can? :destroy, @competition %>
<%= link_to 'Destroy', @competition, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<% if can? :update, @competition %>
<%= link_to 'Programme (pdf)', competition_path(@competition, format: :tex), target: "_blank" %> |
<%= link_to 'Heats (pdf)', heats_path(competition_id: @competition.id, format: :tex), target: "_blank" %> |
<%= link_to 'Lanes (pdf)', lanes_path(competition_id: @competition.id, format: :tex), target: "_blank" %> |
<%= link_to 'Results (pdf)', results_path(competition_id: @competition.id, format: :tex), target: "_blank" %> |
<% end %>
<%= link_to 'Back', competitions_path %>

app/views/competitions/show.tex.erb
\small
\section*{<%= @competition.name %>}
<%= @competition.location %>, <%= @competition.date %>
\section*{Clubs}
<% @competition.invitations.sort { |x, y| x.club.full_name <=> y.club.full_name }.reverse_each do |invitation| %>
<%= invitation.club.name %>\\
<% end %>

\section*{Meet Programme}

<% events = @competition.events.group_by(&:day) %>
<% @competition.days.each do |day| %>
<% if events.include?(day) %>
<% if @competition.length > 1 %>
\subsubsection*{Day <%= day %>}
<% end %>

<%= render events[day].select { |x| x.entries.count > 0 } %>
<% end %>
<% end %>