config/routes.rb
Rails.application.routes.draw do
  resources :splits
  resources :results
  resources :entries
  resources :aims
  resources :seats
  resources :dockets
  resources :relays

  resources :events do
    member do
      post 'list'
      post 'seed'
    end
  end

  resources :invitations
  resources :supports
  resources :qualification_times
  resources :swimmers
  resources :standards
  resources :competitions
  resources :qualifications
  resources :disciplines
  resources :clubs
  resources :strokes
  resources :assignments
  resources :roles

  devise_for :users
  scope :admin do
    resources :users
  end

  get 'heats' => 'heats#index'
  get 'lanes' => 'lanes#index'

  get 'home/index'
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    # what time is it
    @time = Time.zone.now

    # whose birthday is it
    @birthdays = Swimmer.select { |swimmer| swimmer.birthday.day == @time.day and swimmer.birthday.month == @time.month }

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1><%= image_tag('santa-hat.png', size: '120x90') if @time.month == 12 %>Welcome ...</h1>
<h2>... to the Bluefin World of Competitive Swimming.</h2>

<p>It's now <%= @time.strftime('%H:%M:%S (%Z) on %A, %B %d, %Y') %>.</p>

<% if @birthdays.any? %>
  <p>
    <%= image_tag('balloons.png', align: 'middle', width: '30') %>
    Happy Birthday to <%= @birthdays.sample.first_last %>!
    <%= image_tag('balloons.png', align: 'middle', width: '30') %>
  </p>
<% end %>

<% events = Competition.all.group_by(&:relative_date) %>

<% if events[:current].present? %>
  <h3>Today's Events</h3>
  <ul>
    <% events[:current].each do |competition| %>
      <li>
        <%= link_to competition.name, competition %>, <%= competition.location %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if events[:recent].present? %>
  <h3>Recent Events</h3>
  <ul>
    <% events[:recent].last(3).reverse_each do |competition| %>
      <li>
        <%= link_to competition.name, competition %>, <%= competition.location %>
        : <%= time_ago_in_words(competition.date + competition.length) %> ago ...
      </li>
    <% end %>
  </ul>
<% end %>

<% if events[:future].present? %>
  <h3>Upcoming Events</h3>
  <ul>
    <% events[:future].each do |competition| %>
      <li>
        <%= link_to competition.name, competition %>, <%= competition.location %>
        : only <%= time_ago_in_words(competition.date) %> to go ...
      </li>
    <% end %>
  </ul>
<% end %>

<br />
<p>
From here you can access:
<ul>
  <li><%= Club.count %> <%= link_to "Clubs", clubs_path %>;</li>
  <li><%= Competition.count %> <%= link_to "Competitions", competitions_path %>;</li>
  <li><%= Discipline.count %> <%= link_to "Disciplines", disciplines_path %>;</li>
  <li><%= Qualification.count %> <%= link_to "Qualifications", qualifications_path %>.</li>
</ul>
Enjoy!
</p>

<p>Send questions and feedback to <%= mail_to "galaman.mailer@gmail.com" %>.</p>

<p>Visit the <%= link_to 'Bluefin Home Page', 'http://bluefinswimteam.com' %>.</p>

<% 25.times do %>
  <br />
<% end %>