config/routes.rb
Rails.application.routes.draw do
  resources :splits
  resources :results
  resources :entries
  resources :aims
  resources :seats
  resources :dockets
  resources :relays

  resources :events do
    member do
      post 'list'
      post 'seed'
    end
  end

  resources :invitations
  resources :supports
  resources :qualification_times
  resources :swimmers
  resources :standards
  resources :competitions
  resources :qualifications
  resources :disciplines
  resources :clubs
  resources :strokes
  resources :assignments
  resources :roles

  devise_for :users
  scope :admin do
    resources :users
  end

  get 'heats' => 'heats#index'
  get 'lanes' => 'lanes#index'

  get 'home/index'
  root to: 'home#index'
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :entry
    has_one :subject, through: :entry
    has_one :event, through: :entry
      has_one :competition, through: :event
  has_many :splits, dependent: :destroy

  delegate :discipline, :swimmer, :name, :gender,
    :name_and_ages, :club, :invitation, :age, :group, :distance,
    :course, :date, :distance_course_code, :stroke, to: :entry

  attr_accessor :mins, :secs, :cens

  STAGES = %w{ P S F }

  # validates :entry_id, presence: true, uniqueness: true

  ## FIXME: validate to ensure that either comment or time is set, not both.

  def age_in_days
    swimmer.age_in_days(date)
  end

  def symbol
    club.symbol
  end

  def as_json(options = {})
    super(root: false, methods: [:age_in_days, :symbol, :name, :gender])
  end

  # revert natural order if one time is 0 or nil
  def <=> other
    mtime = time.nil? ? 0 : time
    otime = other.time.nil? ? 0 : other.time
    if mtime == otime
      name <=> other.name
    else
      mtime * otime == 0 ? otime - mtime : mtime - otime
    end
  end

  # convert between SC and LC
  def conversion
    time + discipline.differential
  end

  def cens
    time % 100 if time
  end

  def secs
    (time / 100) % 60 if time
  end

  def mins
    time / 6000 if time
  end

  def laps
    splits.each_with_index do |split, i|
      split.lap = (i == 0 ? split.time : split.time - splits[i-1].time)
    end
  end

  def qualify
    return nil if time.nil? or time == 0
    best = nil
    entry.competition.qualifications.includes(:qualification_times).map do |q|
      qt = q.qualification_times.where(discipline_id: discipline, gender: gender).select { |x| x.age_range.include? entry.age }.first
      if qt and qt.time > time and (not best or qt.time < best[:time])
        best = { time: qt.time, qualification: q }
      end
    end
    return best
  end

  def merit
    qu = qualify
    qu ? qu[:qualification].name : ""
  end

  def to_s
    if time.blank?
      '-'
    elsif time == 0
      comment.present? ? comment : '0'
    elsif mins > 0
      sprintf('%d:%02d.%02d', mins, secs, cens)
    else
      sprintf('%d.%02d', secs, cens)
    end
  end

  # coordinates: x = date of competition, y = time in milliseconds
  def x
    date
  end

  def y
    time.blank? ? 0 : 10 * time
  end

  def coordinates
    return x, y
  end

  # convert result into FINA points
  def fina_points
    return if time == 0
    fina_base = Qualification.find_by_name("FINA Base")
    base_time = fina_base.qualification_times.where(
      discipline_id: discipline.id,
      gender: gender
    ).first
    return ((10 * base_time.time.quo(time))**3).to_i if base_time
  end

  # is this result a swimmer's best result up to now?
  def personal_best?
    return false if time.nil? or time == 0
    old = swimmer.results.group_by(&:discipline)[discipline]
    old = old.select { |x| x.date < date and x.time > 0 }
    old.any? ? time < old.map(&:time).min : true
  end

  # return '*' for first time, centiseconds if PB, and nil otherwise.
  def personal_best
    return nil if time.nil? or time == 0
    old = swimmer.results.group_by(&:discipline)[discipline]
    old = old.select { |x| x.date < date and x.time > 0 }
    if old.any?
      diff = old.map(&:time).min - time
      diff > 0 ? diff : nil
    else
      0
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    authorize! :index, Result
    if params[:event_id]
      @event = Event.find(params[:event_id])
      @results = @event.results
    elsif params[:invitation_id]
      @invitation = Invitation.find(params[:invitation_id])
    elsif params[:competition_id]
      @competition = Competition.find(params[:competition_id])
    elsif params[:club_id]
      @club = Club.find(params[:club_id])
      @results = @club.results.includes(entry: [:discipline, { event: [:discipline, :competition] }, { subject: :swimmer }])
    else
      @results = Result.all
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    authorize! :show, @result
  end

  # GET /results/new
  def new
    @result = Result.new
    authorize! :new, @result
    @result.entry = Entry.find(params[:entry_id])
  end

  # GET /results/1/edit
  def edit
    authorize! :edit, @result
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)
    authorize! :create, @result
    if params[:result][:comment].blank?
      @result[:time] = time_from_msc(params[:result])
    else
      @result[:time] = 0
      @result[:place] = ""
    end

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result.event, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    authorize! :update, @result
    if params[:result][:comment].blank?
      @result[:time] = time_from_msc(params[:result])
    else
      @result[:time] = 0
      params[:result][:place] = ""
    end

    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result.event, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    authorize! :destroy, @result
    @result.destroy

    respond_to do |format|
      format.html { redirect_to @result.event, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:entry_id, :time, :comment, :place, :heat, :lane, :stage)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
  def stage_word(stage)
    {
      "P" => "Prelims",
      "S" => "Semis",
      "F" => "Finals",
    }[stage]
  end

  def ordinal_number(obj)
    obj.blank? ? "" : "#{obj}."
  end

  def best_result(results)
    result = results.min
    return result if result.time and result.time > 0
  end
end

app/views/results/_club.html.erb
<h2>Club records by gender.</h2>
<h1><%= club.name %></h1>

<% @results.group_by(&:gender).each do |gender, results_gender| %>

<h3><%= gender_word gender %></h3>

<table class="fact-sheet">
<tr class="times-major">
<th></th>
<% Discipline::STROKES.each do |stroke| %>
  <th style="width:130px"><%= short_stroke_name stroke %></th>
<% end %>
</tr>
<% results_gender.group_by(&:distance_course_code).sort.each do |row, results_row| %>
  <% results = results_row.group_by(&:stroke) %>
  <tr class="pb-lo <%= distance_course(row)[-2,2] %>" align="right">
    <th><%= distance_course(row) %></th>
    <% Discipline::STROKES.each do |stroke| %>
      <td>
        <% if results[stroke] %>
          <% best = best_result(results[stroke]) %>
          <% if best %>
            <%= link_to best, best %><br/>
            <%= best.swimmer.first_last %><br/>
            <span style="font-size:x-small;line-height:16px;vertical-align:top">
              <%= best.date %> :
              <%= best.fina_points %> pts
            </span>
          <% end %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>
<br/>
<br/>
<% end %>

<h2>Club records by age.</h2>
<h1><%= club.name %></h1>

<% @results.group_by(&:age).sort.each do |age, results_age| %>

<% results_age.group_by(&:gender).each do |gender, results_gender| %>

<h3><%= gender_word gender %> (<%= age %>)</h3>

<table class="fact-sheet">
<tr class="times-major">
<th></th>
<% Discipline::STROKES.each do |stroke| %>
  <th style="width:130px"><%= short_stroke_name stroke %></th>
<% end %>
</tr>
<% results_gender.group_by(&:distance_course_code).sort.each do |row, results_row| %>
  <% results = results_row.group_by(&:stroke) %>
  <tr class="pb-lo <%= distance_course(row)[-2,2] %>" align="right">
    <th><%= distance_course(row) %></th>
    <% Discipline::STROKES.each do |stroke| %>
      <td>
        <% if results[stroke] %>
          <% best = best_result(results[stroke]) %>
          <% if best %>
            <%= link_to best, best %><br/>
            <%= best.swimmer.first_last %><br/>
            <span style="font-size:x-small;line-height:16px;vertical-align:top">
              <%= best.date %> :
              <%= best.fina_points %> pts
            </span>
          <% end %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>
<br/>

<% end %>
<% end %>

app/views/results/_event.html.erb
<style>
  .axis, .label {
    font-family: arial;
    font-size: 0.8em;
  }

  path {
    fill: none;
    stroke: black;
    stroke-width: 2px;
  }

  .tick {
    fill: none;
    stroke: black;
  }

  circle {
    opacity: 0.6;
    stroke: none;
    fill: blue;
  }

  div.buttons {
    position: fixed;
    top: 150px;
    right: 20px;
  }

  div.buttons div {
    background-color: rgb(255,156,156);
    padding: 3px;
    margin: 7px;
  }
</style>

<script type="text/javascript">
function draw(data) {

  "use strict";
  var margin = 75,
      width = 1000 - margin,
      height = 600 - margin;

  data = data.results.filter(function(d) { return d.time > 0; })

  var svg = d3.select("div#chart")
    .append("svg")
//      .attr("xmlns", "http://www.w3.org/2000/svg")
//      .attr("xmlns:xlink", "http://www.w3.org/1999/xlink")
      .attr("width", width + margin)
      .attr("height", height + margin)
    .append("g")
      .attr("class", "chart");

  function get_id(d) {
    return d.id;
  }

  // x axis represents age
  function get_age(d) { return d.age_in_days / 365.25; }
  var age_extent = d3.extent(data, get_age);
  var age_scale = d3.scale.linear()
    .range([margin, width])
    .domain(age_extent);
  var age_axis = d3.svg.axis()
    .scale(age_scale);
  svg.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0," + height + ")")
    .call(age_axis);

  svg.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", width)
    .attr("y", height - 6)
    .text("Swimmer's age (years)");

  // y axis represents time
  function get_time(d) {
    return new Date(10 * d.time);  // milliseconds
  }
  var time_extent = d3.extent(data, get_time);
  var time_scale = d3.time.scale()
    .range([margin, height])
    .domain(time_extent);

  var format = d3.time.format("%M:%S");
  var time_axis = d3.svg.axis()
    .scale(time_scale)
    .tickFormat(format)
    .orient("left");
  svg.append("g")
    .attr("class", "y axis")
    .attr("transform", "translate(" + margin + ",0)")
    .call(time_axis);

  svg.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("y", margin + 12)
    .attr("x", -margin)
    .attr("transform", "rotate(-90)")
    .text("Time (mm:ss)");

  // add circles
  svg.selectAll("circle")
    .data(data, get_id)
    .enter()
    .append("a")
    .attr("xlink:href", function(d) { return "entries/" + d.entry_id; })
    .append("circle")
    .attr("cx", function(d) { return age_scale(get_age(d)); })
    .attr("r", 5)
    .append("title")
    .text(function(d) { return d.name; });

  svg.selectAll("circle")
    .transition().duration(1500)
    .attr("cy", function(d) { return time_scale(get_time(d)); })
    .style("fill", 'red');

  // group results by club
  var nested = d3.nest()
    .key(function(d) { return d.symbol; })
    .entries(data);

  var buttons = d3.select("div#chart")
    .append("div")
      .attr("class", "buttons")
    .selectAll("div")
    .data(nested)
    .enter()
    .append("div")
    .text(function(d) { return d.key; });

  buttons.on("mouseover", function(d) {
    buttons.style("background", "rgb(255,156,156)")
      .style("color", "black");
    d3.select(this)
      .style("background", "blue")
      .style("color", "white");
    update(d.values);
  });

  function update(vals) {
    svg.selectAll("circle")
      .data(vals, get_id)
      .style("fill", "blue")
      .exit()
      .style("fill", "red")
  }
}
</script>

<% content_for :level do %>
  <h3><%= @event.competition.name %></h3>
  <ul><%= render partial: "events/level_event", collection: @event.competition.events %></ul>
<% end %>

<%= render 'events/navigation' %>

<% if not @event.is_relay? %>
<h2>Chart</h2>

<div id="chart"></div>
<script type="text/javascript">
  d3.json("<%= event_path(@event, :json) %>", draw);
</script>
<% end %>

<% if can? :update, @event %>
  <div style="float:right">
    <%= button_to 'Sort!', list_event_path(@event) %>
  </div>
<% end %>

<h2>Results.</h2>

<% @results.group_by(&:group).sort.each do |group, results_by_group| %>
  <hr />
  <h3><%= ages_to_words Range.new(*(group.divmod 100)) %></h3>
  <% results_by_group.group_by(&:stage).each do |stage, results| %>
    <h3><%= { 'P' => 'Prelims', 'S' => 'Semis', 'F' => 'Finals' }[stage] %></h3>

    <%# FIXME: what about relays ??? %>
    <%# FIXME: print version %>

    <table class="fact-sheet">
      <tr class="fact-major">
        <th style="width:50px">Plc</th>
        <th style="width:175px">Name</th>
        <th>Age</th>
        <th>Team</th>
        <th style="width:75px">(Seed)</th>
        <th></th>
        <th style="width:75px">Result</th>
        <th></th>
      </tr>
      <%= render results.sort %>
    </table>

  <% end %>
<% end %>

<br />
<hr />

<%= link_to 'Print', results_path(event_id: @event, format: :tex), target: "_blank" %>

<br />
<hr />

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :entry_id %>

<% entry = @result.entry %>
<% competition = entry.competition %>
<% swimmer = entry.swimmer %>

<h3><%= link_to competition.name, competition %> (<%= competition.location %>, <%= competition.date %>)</h3>
<h1><%= link_to swimmer.name, swimmer %> (<%= link_to entry.club.symbol, entry.invitation %>)</h1>

<div>
  <b>Age (F/M):</b>
  <%= entry.age %> (<%= entry.gender %>),
  <b>ID:</b>
  <%= entry.number %>.
<div>
<br />
<br />

<table class="fact-sheet">
  <tr class="times-major">
    <th></th>
    <th>Event</th>
    <th></th>
    <th><%= form.label :place, 'Plc' %></th>
    <th><%= form.label :time, "Result" %></th>
    <th>(Seed)</th>
  </tr>
    <tr class="times-major">
      <th><%= link_to entry.event.pos, entry.event %>.</th>
      <th><%= entry.discipline.nickname %></th>
      <td>
	<% Result::STAGES.each do |stage| %>
          <%= form.label :stage, stage %>
          <%= form.radio_button :stage, stage %>
        <% end %>
      </td>
      <td style="text-align: right;">
        <%= form.text_field :place, size: 4 %>
      </td>
      <td style="text-align: right;">
        <%= form.text_field :mins, size: 2 %>:<%= form.text_field :secs, size: 2 %>.<%= form.text_field :cens, size: 2 %>
      </td>
      <td style="text-align: right;">(<%= entry %>)</td>
    </tr>
</table>
<br />
<br />
  <div class="field">
    <%= form.label :comment %>:
    <ul style="padding: 0; margin: 0; display: inline;">
      <% %w(DQ DNS DNF NS).each do |text| %>
        <li style="list-style:none; display:inline; border: 1px solid blue; background: lightyellow; padding:2px 4px; margin: 4px; border-radius: 4px;">
          <%= form.radio_button :comment, text %>
          <%= text %>
        </li>
      <% end %>
        <li style="list-style:none; display:inline; border: 1px solid blue; background: lightyellow; padding:2px 4px; margin: 4px; border-radius: 4px;">
          <%= form.radio_button :comment, "" %>
          (None)
        </li>
    </ul>
  </div>

<!-- ----------------------------------------------------------
  <div class="field">
    <%= form.label :heat %>
    <%= form.number_field :heat %>
  </div>

  <div class="field">
    <%= form.label :lane %>
    <%= form.number_field :lane %>
  </div>
-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/_invitation.html.erb
<% competition = invitation.competition %>

<h3>
  <%= link_to competition.name, competition %>
  (<%= competition.location %>, <%= competition.dates %>)
</h3>

<h1><%= link_to invitation.club.name, invitation %></h1>

<h3>Results</h3>

<% nr_swims, nr_pbs = 0, 0 %>

<% competition.days.each do |day| %>
<% if competition.length > 1 %>
<h4>Day <%= day %> (<%= competition.date + (day - 1).days %>)</h4>
<% end %>

<% invitation.dockets_for_day(day).group_by(&:gender).each do |gender, dockets| %>
  <% events = dockets.map(&:events).reduce(:|).select { |x| x.day == day }.sort_by(&:pos) %>
<% if events.any? %>
  <div style="overflow-x:auto;">
  <table class="fact-sheet">
    <tr class="times-major">
      <th>Swimmer (<%= gender %>)</th>
      <th>Age</th>
      <% events.each do |event| %>
        <th colspan="2"><%= event.discipline.nickname %></th>
      <% end %>
    </tr>
    <% dockets.sort_by { |x| x.swimmer.name }.each do |docket| %>
      <% swimmer = docket.swimmer %>
      <% entries = docket.entries.group_by(&:event) %>
      <tr class="times-major">
        <td style="white-space: nowrap"><%= link_to swimmer.name, docket %></td>
        <td align="right"><%= docket.age %></td>
        <% events.each do |event| %>
          <td align="right">
  	    <% entry = entries[event].first if entries[event].present? %>
            <% if entry and entry.results.present? %>
              <% result = best_result(entry.results) %>
              <%= link_to result, result if result %>
              </td>
              <td style="white-space: nowrap">
              <% if result and result.time and result.time > 0 %>
                <%= "(#{result.place}.)" if result.place %>
                <% nr_swims += 1%>
                <% if result.personal_best? %>
                  * <% nr_pbs += 1 %>
                <% end %>
                <% qu = result.qualify %>
                <%= qu and qu[:qualification].short %>
              <% end %>
            <% else %>
              </td>
              <td>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  </div>
  <br />
<% end %>
<% end %>
<% end %>

<% if nr_swims > 0 %>
<p>
  <%= pluralize(nr_swims, "Result") %>
  (<%= "%.2f" % [100.0 * nr_pbs/nr_swims] %>% PB)
</p>
<% end %>

<hr/>
<%= link_to 'Back', invitation %>

app/views/results/_result.html.erb
<tr class="fact-major">
  <td align="right"><%= ordinal_number(result.place) %></td>
  <td style="white-space: nowrap"><%= link_to result.entry.name, result.entry.subject %></td>
  <td align="right"><%= result.entry.age %></td>
  <td><%= result.entry.club.symbol %></td>
  <td align="right">(<%= result.entry %>)</td>
  <td align="right">
    <% qu = result.entry.qualify %>
    <% if qu %>
      <%= qu[:qualification].short %>
    <% end %>
  </td>
  <td align="right"><%= link_to result, result %></td>
  <td align="right">
    <% qu = result.qualify %>
    <% if qu %>
      <%= qu[:qualification].short %>
    <% end %>
  </td>
</tr>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<% if @event %>
  <%= render partial: 'event', object: @event %>
<% elsif @invitation %>
  <%= render partial: 'invitation', object: @invitation %>
<% elsif @competition %>
  <%= render partial: 'competition', object: @competition %>
<% elsif @club %>
  <%= render partial: 'club', object: @club %>
<% else %>
  <%= render @results %>
<% end %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<h3><%= link_to @result.competition.name, @result.competition %> (<%= @result.competition.location %>, <%= @result.competition.date %>)</h3>
<h1><%= link_to @result.name, @result.entry.subject %> (<%= link_to @result.symbol, @result.invitation %>)</h1>

<div>
  <b>Age (F/M):</b>
  <%= @result.entry.age %> (<%= @result.gender %>),
  <b>ID:</b>
  <%= @result.swimmer.number %>.
<div>
<br>
<br>

<table class="fact-sheet">
  <tr class="times-major">
    <th></th>
    <th>Event</th>
    <th>(Seed)</th>
    <th>Plc</th>
    <th>Result</th>
    <th></th>
  </tr>
  <tr class="times-major">
    <th><%= link_to @result.event.pos, @result.event %>.</th>
    <th><%= link_to @result.discipline.nickname, swimmer_path(@result.swimmer, discipline_id: @result.discipline) %></th>
    <td style="text-align: right;">(<%= @result.entry %>)</td>
    <td style="text-align: right;"><%= "#{@result.place}." if @result.place %></td>
    <td style="text-align: right;">
      <%= link_to_if(can?(:edit, @result), @result, edit_result_path(@result)) if @result %>
    </td>
    <td><%= @result.stage %></td>
  </tr>
</table>

<% if @result.splits.any? %>
Splits
  <table class="fact-sheet">
    <% @result.laps.each do |split| %>
      <tr class="times-major">
	<td style="text-align: right;"><%= split.length %></td>
	<td style="text-align: right;"><%= time_to_msc split.lap %></td>
	<td style="text-align: right;"><%= time_to_msc split.time %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<hr>

<% if can? :update, @result %>
<%= link_to 'Edit', edit_result_path(@result) %> |
<% end %>
<% if can? :destroy, @result %>
<%= link_to 'Destroy', @result, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', @result.entry.event %>